### Numpy
- numerical 
- its works as creating arrays and mathematical and statistical operations


In [2]:
# importing numpy
import numpy as np


In [52]:
(dir(np))

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [6]:
#creating an array
a1=np.array([1,2,3,4,5])


In [7]:
a1

array([1, 2, 3, 4, 5])

In [8]:
a1.ndim

1

In [9]:
a1.size


5

In [10]:
a1.shape

(5,)

In [12]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])


In [13]:
a2.size


10

In [14]:
a2.shape

(2, 5)

In [15]:
a3=np.arange(1,31)

In [16]:
a3


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
a3.shape

(30,)

In [18]:
a3.reshape(2,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [19]:
a3.reshape(3,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [20]:
a4=a3.reshape(2,15)

In [21]:
a5=a3.reshape(3,10)

In [22]:
a4[1:2,5:6]

array([[21]])

In [23]:
a5[1:2,5:6]

array([[16]])

In [24]:
a5[2:3,7:8]

array([[28]])

In [25]:
a3.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [26]:
a6=a3.reshape(5,6)

In [27]:
a6[3:4,2:3]

array([[21]])

In [28]:
a6[1:3]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [34]:
a5[1:2,1::2]

array([[12, 14, 16, 18, 20]])

In [35]:
a3.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
a7=a3.reshape(6,5)

In [37]:
a7[4: ,2:4]

array([[23, 24],
       [28, 29]])

In [40]:
a7[3::2,2::2]

array([[18, 20],
       [28, 30]])

In [42]:
a7[3:6:2,2:5:2]

array([[18, 20],
       [28, 30]])

In [43]:
a7[0::5,1::3]

array([[ 2,  5],
       [27, 30]])

In [45]:
a7[0:6:5,1:6:3]

array([[ 2,  5],
       [27, 30]])

In [46]:
np.random.random()

0.38569446933566154

In [47]:
np.random.randint(1,20,5)

array([12, 13, 19, 11, 19])

In [48]:
np.random.randn()

-0.06860042444768391

In [54]:
np.random.randint(1,1000,100)

array([283, 678,  85, 140, 314, 914, 236, 381, 963, 268, 286, 654, 774,
       758, 676, 244, 377,  96, 132, 722,  23, 874, 109, 122, 620, 656,
       351, 947, 236, 244, 892, 567, 645, 942,  16, 651, 258, 567, 839,
       176, 582, 237, 144, 582, 527, 827, 731, 151, 490, 565, 979, 233,
       148, 792, 168,  51,  76, 178, 273, 516, 369, 734, 531, 567, 453,
       993,  88, 493, 223, 648, 386, 606,  72,  13, 695, 609,  32, 826,
       571, 844, 111, 459, 292, 779,  49, 385, 636, 648, 811, 427, 106,
       131, 917, 152,  38, 816, 919, 576, 520, 698])

In [56]:
n=np.random.randint(1,100,30)
print(n)
for i in n:
    if i%2==0:
        print(i)

[22 96 38 44 45 83 55 54 71 82 63 34 59 16  5 33 80 48 26  1 65 46 59  4
 47 33 61 98 50 77]
22
96
38
44
54
82
34
16
80
48
26
46
4
98
50


In [57]:
n[n%2==0]

array([22, 96, 38, 44, 54, 82, 34, 16, 80, 48, 26, 46,  4, 98, 50])